version: '3.8'
volumes:
  exercises_upload:
services:
  notebook:
    build: ./notebook
    volumes:
      - ./exercises:/app/exercises
      - ./attendance_id:/app/sync/attendance_id:ro
  jupyter_converter:
    build: ./converter
    volumes:
      - ./exercises:/app/exercises:ro
      - exercises_upload:/app/.exercises
  sync:
    image: "ghcr.io/skiller-whale/learnersync"
    network_mode: "host"
    environment:
      SERVER_URL: https://train.skillerwhale.com
      WATCHER_BASE_PATH: "/app"
      ATTENDANCE_ID_FILE: "/app/sync/attendance_id"
      WATCHED_EXTS: "py"
      IGNORE_DIRS: ".git"
    volumes:
      - ./attendance_id:/app/sync/attendance_id:ro
      - exercises_upload:/app/.exercises:ro
    tty: true
    stdin_open: true
