version: '3.8'
services:
  notebook:
    extends:
      file: common.yml
      service: notebook
    ports:
      # 8888 is used by jupyter notebooks
      - "8888:8888"
  jupyter_converter:
    extends:
      file: common.yml
      service: jupyter_converter
  sync:
    extends:
      file: common.yml
      service: sync
